#pragma once
enum ANIMATION_STATE
{
	eANI_IDLE = 0,
	eANI_RUN_FORWARD,
	eANI_WALK_BACK,
	eANI_WALK_LEFT,
	eANI_WALK_RIGHT,
	eANI_1H_CAST,
	eANI_1H_MAGIC_ATTACK,
	eANI_1H_MAGIC_AREA,
	eANI_BLOCK_START,
	eANI_BLOCK_IDLE,
	eANI_BLOCK_END,
	eANI_DAMAGED_FRONT_01,
	eANI_DAMAGED_FRONT_02,
	eANI_DEATH_FRONT,
	eANI_TOTAL_NUM
};


enum ROUND_STATE 
{
	eROUND_NONE = -1,
	eGAME_START,
	eROUND_ENTER,
	eROUND_START,
	eROUND_DOMINATE,
	eROUND_DEATH_MATCH,
	eROUND_END,
	eROUND_CLEAR,
	eGAME_END,
	eROUND_STATE_NUM
};
enum EVENT_TYPE
{
	EVENT_TIMER = 0,
	EVENT_ROUND_TIMER,
	EVENT_CHANGE_GAMESTATE,
	EVENT_PLAYER_DAMAGE,
	EVENT_PLAYER_ELEMENT,
	EVENT_GAME_GATE,
	EVENT_DEATHMATCH,
	EVNET_TOTAL_NUM
};
enum LogType
{
	LOGTYPE_CONNECTION,
	LOGTYPE_DISCONNECTION,
	LOGTYPE_GAME_SYSTEM,
	LOGTYPE_SERVER_SYSTEM,
	LOGTYPE_OPERATION_SYSTEM,
	LOGTYPE_PACKET,
	LOGTYPE_TOTAL_NUM
};
enum ElementType
{
	ELEMENT_TYPE_LIGHT		  =0,
	ELEMENT_TYPE_FIRE			,
	ELEMENT_TYPE_WIND			,
	ELEMENT_TYPE_ICE			,
	ELEMENT_TYPE_DARK			,
	ELEMENT_TYPE_ELECTRIC		,
	ELEMENT_TYPE_TOTAL_NUM
};